# Generated by Django 5.2 on 2026-02-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tag_blogpost_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to save as draft'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title (auto-generated from text if empty)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(help_text='Your note content'),
        ),
    ]
